### ISSUE TITLE
-fstack-protector issues

### ISSUE THREAD

**Issue by kevans91** [seanbruno/qemu-bsd-user#111]
Originally reported in #74 and since worked around in ports; qemu does something to irritate the stack protector. The ports workaround is effective for the old 2.x version still in ports, but 3.1 is apparently much worse about it - we hit ssp failure even before tcg is fully initialized, and even earlier sometimes if -L is used - even without the -strong variant.

We'll need to diagnose and fix it, if possible, as it consistently fails as of now.

**Comment by kevans91** [comment]
As of base r354672, these should be alleviated. We'll probably want to wait until the pkg build infrastructure can be updated to >= r354672 before we switch to rebase-3.1, assuming my testing pans out (which I have no reason to suspect it won't, at this point).

@ant1 @seanbruno how often do those particular cluster machines update? Does portmgr have some leniency in requesting one-off updates when it would benefit from stuff like that, or is it an across-the-board policy from clusteradm@?

**Comment by kevans91** [comment]
Hmm... the other side of that is that the qemu-user-static package will also need to be built against a libc >= r354672.

**Comment by bsdimp** [comment]
Won't we need to MFC it?

Alternatively, is there a way we can hack the priority for the qemu ctor that creates the thread?

**Comment by kevans91** [comment]
> Won't we need to MFC it?

Yeah, the more I think about it- the more I think we really should.

> Alternatively, is there a way we can hack the priority for the qemu ctor that creates the thread?

Unfortunately not- the SSP ctor is at the end of the line, so we can't move the qemu ctor after it. We can hack the thread creation stuff to artificially delay or some other sketchy stuff to kind of avoid it, but we're hitting up Ugly 2.0 here and most paths we *could* take won't let us allow user control over SSP flags and/or revert the flag hacks already committed to devel/glib20 and emulators/...mumble...
