### ISSUE TITLE
TARGET_HW_MACHINE_ARCH is hard-coded as armv6

### ISSUE THREAD

**Issue by ghost** [seanbruno/qemu-bsd-user#53]
#define TARGET_HW_MACHINE_ARCH  "armv6"
https://github.com/seanbruno/qemu-bsd-user/blob/bsd-user/bsd-user/arm/target_syscall.h#L34

We should fix that for armv7?

**Comment by seanbruno** [comment]
Ooo, yeah.  Hrm.  That *is* a problem.
