### ISSUE TITLE
Capsicumized wc fails on mips64 emulation

### ISSUE THREAD

**Issue by seanbruno** [seanbruno/qemu-bsd-user#71]
After the recent capsicumization of wc in freebsd-current, wc fails to run as I expect there are syscalls that we just don't support/emulate here and the default operations need love on mips64.

Build a mips64 jail with poudriere, start it and enter it:
```

poudriere jail -c -j mips64test -m svn -v head -a mips.mips64 -x
poudriere jail -s -j mips64-test
jexec mips64-test-default
```

Run a bare "wc" with no input against /dev/null. It will hang until I try to get a  siginfo dump from it via ctrl-t and then it will emit an error.

```
root@13mips64-test-default:/ # wc /dev/null
load: 0.06  cmd: qemu-mips64-static 65433 [select] 1.93r 0.01u 0.00s 0% 12104k
wc: Unable to init casper: Resource temporarily unavailable
```

Previously to the changes in head, wc would return something sensible:
```
root@13mips64-default:/ # wc /dev/null
       0       0       0 /dev/null
```

**Comment by seanbruno** [comment]
Ran this command on native hardware and I get a deviation on my EdgeRouter Light.

```
root@ERL:~ # wc -l /dev/null
wc: /dev/null: open: Function not implemented
```

**Comment by ant1** [comment]
head(1) is now broken in qemu-mips64 too (also after caspsicumization)
