### ISSUE TITLE
casper issue on mips*

### ISSUE THREAD

**Issue by ant1** [seanbruno/qemu-bsd-user#90]
There are still issues with capsicumized stuff on mips*,  for instance when using strings or nm:

```
t2h Unsupported ancillary data: 20/65535
qemu:handle_cpu_signal received signal outside vCPU context @ pc=0x6028a2c1
uncaught target signal 6 (Abort trap) - core dumped
nm: failed to initialize fileargs: Invalid argument
```

**Comment by kevans91** [comment]
Fixed by above-referenced PR. The first cmsg was fine, but any subsequent cmsg was off as we screwed up the alignment.

**Comment by kevans91** [comment]
The fix for this hit the ports tree in r517350.
